title: Robert Carlton
logo: /images/OvalHeadshot.png
descripton: Leveraging data analytics (regression, ML, AI and beyond) to drive actonable insights for marketers
show_downloads: true
theme: jekyll-theme-minimal
